# Generated by Django 5.1.4 on 2025-02-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_alter_match_away_score_alter_match_home_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualscore',
            name='away_player_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individualscore',
            name='home_player_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
