# Generated by Django 5.1.4 on 2025-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_individualscore_away_player_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualscore',
            name='away_player_name',
        ),
        migrations.RemoveField(
            model_name='individualscore',
            name='home_player_name',
        ),
        migrations.AlterField(
            model_name='individualscore',
            name='away_player',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individualscore',
            name='home_player',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
