# Generated by Django 5.1.4 on 2025-01-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_nickname_profile_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_default.jpeg', null=True, upload_to='profile_pics/'),
        ),
    ]
