# Generated by Django 5.1.4 on 2025-01-09 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_team_image'),
        ('users', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='teams.team'),
        ),
    ]
