# Generated by Django 5.1.4 on 2025-02-20 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_division_num_weeks_division_start_date'),
        ('users', '0006_remove_customuser_team_profile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='teams.team'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
