# Generated by Django 5.1.4 on 2025-02-26 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_team_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_wins', models.IntegerField(default=0, null=True)),
                ('match_losses', models.IntegerField(default=0, null=True)),
                ('game_wins', models.IntegerField(default=0, null=True)),
                ('game_losses', models.IntegerField(default=0, null=True)),
                ('total_games', models.IntegerField(default=0, null=True)),
                ('win_to_loss_ratio', models.CharField(default='0:0', max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
