# Generated by Django 5.1.4 on 2025-02-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='match_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='match_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
    ]
