# Generated by Django 5.1.4 on 2025-03-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_player_game_losses_alter_player_game_wins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='team',
        ),
    ]
