# Generated by Django 5.1.4 on 2025-01-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='home_or_away',
            field=models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away')], default='HOME', max_length=5),
        ),
    ]
