# Generated by Django 5.1.1 on 2025-01-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_fixture_home_or_away'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='home_or_away',
        ),
    ]
