# Generated by Django 5.1.1 on 2025-01-17 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_remove_fixture_home_or_away'),
        ('teams', '0005_division_num_weeks_division_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='bye_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bye_fixtures', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='teams.team'),
        ),
    ]
