# Generated by Django 5.1.1 on 2025-01-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_fixture_bye_team_alter_fixture_away_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
