# Generated by Django 5.1.4 on 2025-02-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='winner',
            new_name='champion',
        ),
    ]
