# Generated by Django 5.1.4 on 2025-02-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_rename_winner_tournament_champion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='champion',
            new_name='winner',
        ),
    ]
